shell = "zsh"

apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
autoload = "{% for file in files %}autoload -Uz \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.dotfiles-zsh-config]
local = "~/.config/zsh/config"
use = ["main.zsh"]
apply = ["source"]

[plugins.dotfiles-zsh-lazy-config]
local = "~/.config/zsh/config"
use = ["{!sync,*}.zsh"]

[plugins.dotfiles-zsh-aliases]
local = "~/.config/zsh/aliases"

[plugins.dotfiles-zsh-functions]
local = "~/.config/zsh/functions"
use = ["*"]
apply = ["autoload"]

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"
apply = ["source"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-search-multi-word]
github = "zdharma/history-search-multi-word"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.aws_zsh_completer]
remote = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"
