shell = "zsh"

apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
autoload = "{% for file in files %}autoload -U \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-search-multi-word]
github = "zdharma/history-search-multi-word"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.aws_zsh_completer]
remote = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"

[plugins.dotfiles-functions]
local = "~/.zsh/functions"
apply = ["autoload"]

[plugins.dotfiles-aliases]
local = "~/.zsh/aliases"
apply = ["autoload"]

[plugins.dotfiles-config]
local = "~/.zsh/config"
