shell = "zsh"

apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit -d \"$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION\""

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"
apply = ["source"]

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
use = ["{{ name }}.zsh"]
apply = ["source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-replace-multiple-dots]
github = "momo-lab/zsh-replace-multiple-dots"

[plugins.navi]
inline = "zsh-defer eval \"$(navi widget zsh)\""

[plugins.aws_zsh_completer]
remote = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"

[plugins.dotfiles-eager]
local = "~/.config/zsh/eager"
apply = ["source"]

[plugins.dotfiles-lazy]
local = "~/.config/zsh/lazy"
